name: recal_mobile2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  json_annotation: ^4.8.0
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  http: ^0.13.4
  flutter_native_timezone: ^2.0.0
  flutter_background_service: ^2.4.6
  permission_handler: ^10.2.0
  workmanager: ^0.5.1
  shared_preferences: ^2.1.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  firebase_ui_auth: ^1.3.0
  go_router: ^7.0.0
  firebase_messaging: ^14.5.0
  cloud_firestore: ^4.5.3
  font_awesome_flutter: ^10.4.0
  equatable: any

  # google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  mocktail: ^0.3.0
  fake_cloud_firestore: ^2.4.1+1

flutter:
  uses-material-design: true
