// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCilwXjiNjkWjzLADdYGoDoX1EXNrz7Bzs',
    appId: '1:246821395081:web:670ab7322a47b424200458',
    messagingSenderId: '246821395081',
    projectId: 'recal-25c33',
    authDomain: 'recal-25c33.firebaseapp.com',
    storageBucket: 'recal-25c33.appspot.com',
    measurementId: 'G-YP6L0FN87P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADo_OKYE8zFWNxkIfQItDXtnO9_FGWie8',
    appId: '1:246821395081:android:10aecb5c6183d66c200458',
    messagingSenderId: '246821395081',
    projectId: 'recal-25c33',
    storageBucket: 'recal-25c33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp598UN5VNg4TWKbo4DdnqmnWepLfQew4',
    appId: '1:246821395081:ios:2086667305ae41e0200458',
    messagingSenderId: '246821395081',
    projectId: 'recal-25c33',
    storageBucket: 'recal-25c33.appspot.com',
    iosClientId: '246821395081-bm3es383gqf41n8ej5rddtm493u4umcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.recalMobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp598UN5VNg4TWKbo4DdnqmnWepLfQew4',
    appId: '1:246821395081:ios:2086667305ae41e0200458',
    messagingSenderId: '246821395081',
    projectId: 'recal-25c33',
    storageBucket: 'recal-25c33.appspot.com',
    iosClientId: '246821395081-bm3es383gqf41n8ej5rddtm493u4umcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.recalMobile2',
  );
}
